name: GitHub CI
on:
  push:
    types: [opened, synchronize]
    branches: [test]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows64_build:
    name: Windows x86_64 Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-libevent mingw-w64-x86_64-pcre2 patch
          msystem: MINGW64
          path-type: inherit
      - name: Add commit id into version
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
      - name: Build
        run: bash scripts/build.windows.release.sh
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: subconverter_win64
          path: subconverter/
      - name: Package Release
        run: 7z a subconverter_win64.7z subconverter/
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Alpha
          release: true
          files: subconverter_win64.7z
